# #################################
# Training ECAPA-TDNN embeddings for Accent identification (LID) of English Data.
#
# Authors:
#  * For SLT Juan Pablo and Sara
# #################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1986
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Set up folders for reading from and writing to
# Dataset will be downloaded to the `data_folder`
# data_folder: !PLACEHOLDER # e.g. /localscratch/common_voice_kpd/
data_folder: /remote/idiap.svm/resource.dataset04/CommonVoice
csv_prepared_folder: data/
output_folder: !ref results/W2V2/augmented_lv60k/<seed>
save_folder: !ref <output_folder>/save
rir_folder: !ref data/rir_folder
train_log: !ref <output_folder>/train_log.txt
device: 'cuda:0'
skip_prep: True
# max audio lenth allowed, higher than this is dropped
max_audio_length: 10

# URL for the biggest Fairseq english wav2vec2 model.
wav2vec2_hub: facebook/wav2vec2-large-960h-lv60-self #dimension of this model is 1024
# wav2vec2_hub: "facebook/wav2vec2-base" #dimension of this model is 768

# The train logger writes training statistics to a file, as well as stdout.
train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

error_stats: !name:speechbrain.utils.metric_stats.MetricStats
    metric: !name:speechbrain.nnet.losses.classification_error
        reduction: batch

# variable to control whether to apply augmentation or not:
apply_augmentation: True

# Training Parameters
sample_rate: 16000
number_of_epochs: 30
batch_size: 4 # it should be 16, but we do half as there's data augmentation on top

# set to TRUE to freeze all wav2vec2
freeze_wav2vec2: False
# set to true to freeze the CONV part of the wav2vec2 model
# We see an improvement of 2% with freezing CNNs
freeze_wav2vec2_conv: True

# Model parameters
encoder_dim: 1024

# Number of accents
n_accents: 16

# Dataloaders
train_dataloader_options:
    batch_size: !ref <batch_size>
    num_workers: 2  # 2 on linux but 0 works on windows    
    drop_last: True
    shuffle: True

test_dataloader_options:
    batch_size: !ref <batch_size>
    shuffle: False

# Added noise and reverb come from OpenRIR dataset, automatically
# downloaded and prepared with this Environmental Corruption class.
env_corrupt: !new:speechbrain.lobes.augment.EnvCorrupt
    openrir_folder: !ref <rir_folder>
    openrir_max_noise_len: 3.0  # seconds
    babble_prob: 0.0
    reverb_prob: 1.0
    noise_prob: 1.0
    noise_snr_low: 0
    noise_snr_high: 15
    rir_scale_factor: 1.0

# Adds speech change + time and frequency dropouts (time-domain implementation)
# A small speed change help to improve the performance of speaker-id as well.
augmentation: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
    sample_rate: !ref <sample_rate>
    speeds: [95, 100, 105]

# Model parameters
activation: !name:torch.nn.GELU
dnn_layers: 2
dnn_neurons: 1024
freeze_wav2vec: True

# front end Wav2vec2 - main model
wav2vec2: !new:speechbrain.lobes.models.huggingface_wav2vec.HuggingFaceWav2Vec2
    source: !ref <wav2vec2_hub>
    output_norm: True
    freeze: !ref <freeze_wav2vec2>
    freeze_feature_extractor: !ref <freeze_wav2vec2_conv>
    save_path: !ref <save_folder>/wav2vec2_checkpoint

avg_pool: !new:speechbrain.nnet.pooling.StatisticsPooling
    return_std: False

output_mlp: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <encoder_dim>
    n_neurons: !ref <n_accents>
    bias: False

# The first object passed to the Brain class is this "Epoch Counter"
# which is saved by the Checkpointer so that training can be resumed
# if it gets interrupted at any point.
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

# Objects in "modules" dict will have their parameters moved to the correct
# device, as well as having train()/eval() called on them by the Brain class.
modules:
    env_corrupt: !ref <env_corrupt>
    augmentation: !ref <augmentation>
    wav2vec2: !ref <wav2vec2>
    output_mlp: !ref <output_mlp>

model: !new:torch.nn.ModuleList
   - [!ref <output_mlp>]

# Additive Angular Margin
# compute_cost: !new:speechbrain.nnet.losses.LogSoftmaxWrapper
#     loss_fn: !new:speechbrain.nnet.losses.AdditiveAngularMargin
#         margin: 0.2
#         scale: 30

# standard NLL loss
compute_cost: !name:speechbrain.nnet.losses.nll_loss

log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

# Learning rates for normal optimizer and W2V2 model
lr: 0.0001
lr_wav2vec2: 0.00001

# Optimizers class 
opt_class: !name:torch.optim.Adam
    lr: !ref <lr>

wav2vec2_opt_class: !name:torch.optim.Adam
    lr: !ref <lr_wav2vec2>

# LR annealing objects
lr_annealing: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr>
    improvement_threshold: 0.0025
    annealing_factor: 0.9
    patient: 0

lr_annealing_wav2vec2: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr_wav2vec2>
    improvement_threshold: 0.0025
    annealing_factor: 0.9

# This object is used for saving the state of training both so that it
# can be resumed if it gets interrupted, and also so that the best checkpoint
# can be later loaded for evaluation or inference.
checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        wav2vec2: !ref <wav2vec2>
        lr_annealing_output: !ref <lr_annealing>
        lr_annealing_wav2vec2: !ref <lr_annealing_wav2vec2>
        counter: !ref <epoch_counter>